
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const REQUEST_USER_CONTACT_LIST = 'REQUEST_USER_CONTACT_LIST';
export const REQUEST_USER_CONVERSATIONS_LIST = 'REQUEST_USER_CONVERSATIONS_LIST';
export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const REQUEST_NUMBER_OF_CONTACT_REQUESTS = 'REQUEST_NUMBER_OF_CONTACT_REQUESTS';