
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const REQUEST_USER_CONTACT_LIST = 'REQUEST_USER_CONTACT_LIST';
export const REQUEST_USER_CONVERSATIONS_LIST = 'REQUEST_USER_CONVERSATIONS_LIST';
export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const ACEPT_CONTACT_REQUEST = 'ACEPT_CONTACT_REQUEST';
export const REJECT_CONTACT_REQUEST = 'REJECT_CONTACT_REQUEST';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_CONTACT_REQUESTS = 'UPDATE_CONTACT_REQUESTS';
export const SET_REQUEST_MODAL_WINDOW = 'SET_REQUEST_MODAL_WINDOW';